name: spreed-webrtc
version: 0.28.1oparoz1
summary: WebRTC audio/video calls and conferences
description: Spreed WebRTC implements a WebRTC audio/video call and conferencing server and web client
grade: stable
confinement: strict

apps:
  spreed-webrtc:
    command: bin/start
    daemon: simple
    plugs: [network, network-bind]

parts:
  spreed:
    plugin: autotools
    source: https://github.com/strukturag/spreed-webrtc
    source-type: git
    source-branch: release-0.28
    build-packages: [golang-go, nodejs]
  glue:
    plugin: dump
    source: src
    organize:
      start: bin/start
      redirector: bin/redirector
  config:
    plugin: dump
    source: src
    organize:
      config.py: bin/config